### ISSUE TITLE
Option to not minimize to tray when closing?

### ISSUE THREAD

**Issue by brodymillington** [SrWither/DiscordBSD#11]
Hey,

just wondering if there was a way of adding an option to totally exit DiscordBSD when closing the window instead of going down to the tray area? Similar to how the official app has the options for Linux integration?

And if the option is hidden away and i didn't see it, i apologies lol 

Thanks for this port though, really good quality  :+1:

**Comment by SrWither** [comment]
For now there is no such option, but it is a good idea, I will implement it soon

**Comment by SrWither** [comment]
Well, this option was already implemented a long time ago, I forgot to mention it.
