### ISSUE TITLE
Couldn't build with node20, needed node18

### ISSUE THREAD

**Issue by sukibaby** [SrWither/DiscordBSD#14]
I just set up FreeBSD 14.1-RELEASE as a fresh install and installed the prerequisites to build DiscordBSD, however I got an error stating that node18 would conflict with files I already have installed at the location node20 is installed. I ultimately ended up removing node20 and installing node18 with pkg. Then I could finish building.

I didn't want to submit a PR changing the README because I wasn't sure if this was intended/expected behavior.

**Comment by grahamperrin** [comment]
Similar here, with FreeBSD-CURRENT and _yarn_-node20.

I stopped the build. 

I'm confused, because my previous attempt to build did not present the conflict; also because <https://github.com/SrWither/DiscordBSD?tab=readme-ov-file#build-dependencies> expresses node20 as a build requirement.

**Comment by SrWither** [comment]
Currently it should compile without problem with node20. the latest version of discordbsd use electron30 and node20
