### ISSUE TITLE
[Question] electron.mk instructions

### ISSUE THREAD

**Issue by ctxmc** [SrWither/DiscordBSD#18]
Hello! It is not clear to me what should I do with 
https://github.com/tagattie/FreeBSD-Electron/blob/master/Mk/Uses/electron.mk

Should I raw copy it to a file named electron.mk and place it into /usr/ports/Mk... etc?
Should I intall the whole FreeBSD-Electron? Can this be more clear?

**Comment by SrWither** [comment]
Well, you must download it to that file and put it in that directory, since it does not come in the PKG package

The use is for the makefile that is responsible for packaging discordbsd

``
USES=electro:30
``
