### ISSUE TITLE
Only "Default" selectable for Input and Output Audio Device

### ISSUE THREAD

**Issue by Lockna** [SrWither/DiscordBSD#5]
Installed the newest version of DiscordBSD and works fine, except that in the Voice Settings I can only set the Input and Output Device to Default.
Which works for the output, but since I got headphones and not a headset, I can't get a working input.
In the meantime I have to use Discord in Web.
Is there a fix available?

**Comment by SrWither** [comment]
I'm not sure, since the devices come directly from electron (chrome)

**Comment by SrWither** [comment]
I'm not sure, the devices come directly from electron (chrome) And it probably just detects that.

**Comment by SrWither** [comment]
I'm not sure, the devices come directly from electron (chrome) And it probably just detects that.

**Comment by Lockna** [comment]
Hmm, okay. Thank you, then I can the Issue can be closed.

**Comment by brodymillington** [comment]
> Hmm, okay. Thank you, then I can the Issue can be closed.

Not sure if you're still using this or not, but i originally had the same problem as you, i solved it by using virtual_oss, using something like below, whether that will help you or not. 

virtual_oss_enable="YES"
virtual_oss_dsp="-T /dev/sndstat -S -i 8 -C 2 -c 2 -r 48000 -b 24 -s 8.0ms -c 2 -O /dev/dsp0 -R /dev/dsp3 -d dsp -t dsp.ctl"

Just make sure you adjust the devices to match yours with -O being output and -R input. Also check the man page for virtual_oss as there a couple of other steps required.

**Comment by Lockna** [comment]
Thanks, will try that
