### ISSUE TITLE
bb86df9 cp: share/discordbsd/*: No such file or directory

### ISSUE THREAD

**Issue by grahamperrin** [SrWither/DiscordBSD#7]
Close #6 in favour of this? 

```text
% ./install.sh
Installing DiscordBSD
Removing old installation...
cp: share/discordbsd/*: No such file or directory
Done!
% which discordbsd
discordbsd: Command not found.
% which DiscordBSD
DiscordBSD: Command not found.
% which discord
/home/grahamperrin/.local/bin/discord
% discord
/home/grahamperrin/.local/bin/discord: ./discord/discordbsd: not found
% git log --oneline -n 1
bb86df9 (HEAD -> main, origin/main, origin/HEAD) fix install script
% 
```

**Comment by SrWither** [comment]
you are running the install script without building the project
you have 2 options:
- download the version compiled by me from the release (which already has the permission denied error corrected)
- or compile it by hand, for this you need to install `electron27` and have `devel/electron27` in the ports tree, install `app-builder` by pkg and run the `build.sh` file
