### ISSUE TITLE
Which FreeBSD version are supported?

### ISSUE THREAD

**Issue by SlySven** [SrWither/DiscordBSD#9]
I'm currently running FreeBSD 13.2-RELEASE-p11 on an AMD64 processor (I am about to upgrade to 13.3 ...!) I understand I need to unzip the `.zip` file provided as a "Release" into a part of the file-system that is mine and then run the `install.sh` script in the root of the unzipped archive. Should this be sufficient to get me a working Discord application or are other packages required? I mean I find a `discord` script inside a `./.local/bin` off my home directory but I then get:
```sh
[stephen@Ripley ~]$ ./.local/bin/discord 
./.local/bin/discord: node: not found
ld-elf.so.1: /usr/home/stephen/.local/share/discordbsd/discord/DiscordBSD: Undefined symbol "__libc_start1@FBSD_1.7"
```
So I then proceed to install `node`:
```sh
[stephen@Ripley ~]$ sudo pkg install node
Password:
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
The following 3 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        c-ares: 1.24.0
        node: 20.11.1_1
        node20: 20.11.1

Number of packages to be installed: 3

The process will require 44 MiB more space.
9 MiB to be downloaded.

Proceed with this action? [y/N]: y
[1/3] Fetching node-20.11.1_1.pkg: 100%    1 KiB   1.1kB/s    00:01    
[2/3] Fetching c-ares-1.24.0.pkg: 100%  184 KiB 188.8kB/s    00:01    
[3/3] Fetching node20-20.11.1.pkg: 100%    9 MiB   9.5MB/s    00:01    
Checking integrity... done (0 conflicting)
[1/3] Installing c-ares-1.24.0...
[1/3] Extracting c-ares-1.24.0: 100%
[2/3] Installing node20-20.11.1...
[2/3] Extracting node20-20.11.1: 100%
[3/3] Installing node-20.11.1_1...
[3/3] Extracting node-20.11.1_1: 100%
=====
Message from node20-20.11.1:

--
Note: If you need npm (Node Package Manager), please install www/npm.
```
Okay I thought maybe that'll sort it - but no:
```
[stephen@Ripley ~]$ ./.local/bin/discord 
ld-elf.so.1: /usr/home/stephen/.local/share/discordbsd/discord/DiscordBSD: Undefined symbol "__libc_start1@FBSD_1.7"
```

Some DuckDuckGo-ing (better than Googling as it doesn't telephone home about your browsing) suggest that this is a problem because of OS version mismatches between the system the binary was compiled on and that on which it is being attempted to run. Is this the case and if so - what precisely is the pre-built binary compatible with?

**Comment by SrWither** [comment]
DiscordBSD is compiled in Freebsd 14, this is probably why it does not work in Freebsd 13, a solution would be to compile it

**Comment by SlySven** [comment]
Ah, I've just got back - it was sufficient to upgrade to **13.3-RELEASE-p1** to enable it to run...

**Comment by SrWither** [comment]
So everything is already working?

**Comment by SlySven** [comment]
For me - yeah - I'm just wondering how this can be handled going forward - **13.2-RELEASE** is not EOL for a couple of months yet: (referring to https://www.freebsd.org/security/#sup ) OTOH if you are building and uploading the binaries yourself you must be limited in what you can build for others...

**Comment by SrWither** [comment]
Partly yes, since the binaries that I provide are from the latest version of Freebsd, but there is always the option for someone to compile it on their own, anyway, if everything is in order I proceed to close the issues
